.TH skippy 1 2020-09-20 "Cape Town" "Vim go brrr"
.SH NAME
Stephen "skippy" Cochrane
.SH SYNOPSIS
.B skippy --verbose
.SH CONTACT
Email: skippycochrane@gmail.com
.br
Twitter: @posix_patrol
.br
Mastadon: @skippy@fosstodon.org
.SH NOTE
.PP
This document should be viewed by running
.B man\ <(curl\ -s\ \%http://skiqqy.xyz/skippy.1)
.SH DESCRIPTION
.PP
I am currently studying Computer Science at Stellenbosch University, and am
currently in my third year.
.PP
I have a massive love for Software Development (specifically lower level systems)
and the GNU/Linux ecosystem. I am an advocate of the FOSS movement, and believe
in it's ideals.
.PP
Primary skills include programming in C (langauge of choice), bash (scripting),
python, java. I am proficient in backend web development (either in C, java or
python) as well as working with databases.
.SH WORK EXPERIENCE
.SS At/for Stellenbosch University
.PP
I have tutored and or "demi'd" multiple courses for SU, those including,
.IP
\(bu First Year Mathematics
.IP
\(bu Second Year Computer Science
.SH SELECTED ARTIFACTS
.PP
These projects are hosted on a private repository, since many of these
projects are re-used by SU, and hence must be hosted privetly to prevent students
from plagiarising.
.PP
If you are interested in viewing these, please send me an email, and I can provide
you with a .tar of the project.
.SS ALAN Compiler
.PP
ALAN is a pascal like langauge, and my second year Computer Science project
was to write a compiler for the ALAN language, for more information feel free to
read the spec. The compiler is written in C.
.SS Othello Bot
This project was to create a bot to play the game Othello, the bot makes use of
a negamax trea search with alpha beta pruning to find optimal moves. Written in C,
using MPI API.
.SS OnPoint
.PP
OnPoint is a food review website, that allows users to view reviews on certain
websites, as well as create an account, and follow friends, and see thier favorite
restuarants.
.PP
OnPoint is written using a python backend (running on flask), neo4j DB, redis
and Vue.js
.SS
Huffman Encoder
.PP
A compression tool using the Huffman algorithm, written in x86_64 assembly.
.SH PRIVATE PROJECTS
.SS
cmesg
.PP
A messaging application using a server written in C, and a client written in java,
there are plans to extend cmesg to also support VoIP.
.PP
cmesg is hosted at
.I https://github.com/skippy404/cmesg
.SS
C45DiscordBot
.PP
A simple discord bot written in python, plans to extend it to play music, host
files etc.
.PP
C45DiscordBot is hosted at
.I https://github.com/skippy404/C45DiscordBot
.SH
BUGS
.PP
Start too many side projects, instead of finishing them.
.PP
Endlessing ricing my desktop subtle plug ->
.I
https://github.com/skippy404/dwm
.SH
SEE ALSO
.I \%http://yggpi.co.za/
.br
.I \%https://github.com/skippy404/
.br
.I \%https://twitter.com/posix_patrol
